language: node_js
node_js:
  - "5.0.0"
before_install: npm install -g grunt-cli
install: npm install
sudo: false
after_success:
  - coveralls
cache:
  directories:
    - node_modules
notifications:
  email: false
