language: node_js
node_js:
  - "5.0.0"
before_install: npm install -g grunt-cli

deploy:
 provider: releases
 api_key: "$GITHUB_OAUTH_TOKEN"
 file: "README.md"
 skip_cleanup: true
 draft: true
 
install: npm install
sudo: false
after_success:
  npm run-script coverage
cache:
  directories:
    - node_modules
notifications:
  slack: bottry:qGLlvCPcGHJp6kcmmPuCcHGd
  webhooks:
    - http://ci-alarm.herokuapp.com/
